// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdkvipzovzjpyeusyque.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhka3ZpcHpvdnpqcHlldXN5cXVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTI0MDMsImV4cCI6MjA3MjU4ODQwM30.L3Y_K5b4VoUOxKTgeE97kLzz8zWhHOf95DC2BjbYjEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});